### ISSUE TITLE
Feature Request: Service Account Key from Environment (not file)

### ISSUE THREAD

**Issue by tedsecretsource** [pprados/langchain-googledrive#2]
This is a feature request to use a service account key that is defined in an environment variable. This is not a request to use the _path_ to the service account key but to have the actual key in the environment.

Storing credentials on the filesystem can be problematic from a security perspective and for services like Heroku's Container stack, the credentials would have to be part of the repository in order to make it into a deployed production environment. This is because filesystems on the Container stack are ["ephemeral"](https://devcenter.heroku.com/articles/active-storage-on-heroku#ephemeral-disk).

I've worked around LangChain's GoogleDriveLoader file restriction with the following class override. Maybe it can help you?

```python
class CustomGoogleDriveLoader(GoogleDriveLoader):
    """Loads Google Drive credentials from the environment instead of from a file."""
    def _load_credentials(self):
        try:
            creds = service_account.Credentials.from_service_account_info(
                json.loads(os.environ['GOOGLE_SERVICE_ACCT_KEY']),
                scopes=['https://www.googleapis.com/auth/drive.readonly']
            )
            return creds
        except ValueError:
            return super()._load_credentials()
```

I suspect the change would have to be made somewhere near [here](https://github.com/pprados/langchain-googledrive/blob/3f95bec08053c88d12e5446567e4904332913f4f/langchain_googledrive/utilities/google_drive.py#L743)

Thanks. I'm looking forward to trying this out but not being able to store the whole key in the environment is a showstopper for me.

Ted

**Comment by pprados** [comment]
Thanks.
I update the source with GOOGLE_ACCOUNT_SERVICE_KEY.
I must fix two others bugs, and i will publish a new version.

```
        if "GOOGLE_ACCOUNT_SERVICE_KEY" in os.environ:
            return service_account.Credentials.from_service_account_info(
                json.loads(os.environ['GOOGLE_ACCOUNT_SERVICE_KEY']),
                scopes=scopes
            )
        elif api_file:
     
```
