### ISSUE TITLE
How to fetch file from google drive using file_id

### ISSUE THREAD

**Issue by adilkhatri1123** [pprados/langchain-googledrive#4]
Hi,

While I can fetch files of a folder by passing folder_id, I want to know how I can do the same with the file IDs,

I tried using file_ids, it fetches the file perfectly but at the same time I get a warning that it has been deprecated and it tells me to use a template instead. Can you show some examples?

**Comment by pprados** [comment]
Use the template `gdrive-by-name-in-folder`, `folder_id` and filename in `query`.

```
loader = GoogleDriveLoader(
    folder_id=folder_id,
    template="gdrive-by-name-in-folder",  # Default template to use
    query="MyFileName.pdf",
    num_results=2,  # Maximum number of file to load
    supportsAllDrives=False,  # GDrive `list()` parameter
)
```

**Comment by pprados** [comment]
The [list()](https://developers.google.com/drive/api/reference/rest/v3/files/list?hl=fr) api of Google Drive, can not find a find by id.
See the [filter syntax](https://developers.google.com/drive/api/guides/search-files).
