### ISSUE TITLE
Include hyperlinks from GDocs

### ISSUE THREAD

**Issue by mbastian** [pprados/langchain-googledrive#5]
Hi, and thanks again for the work on this library!

I was wondering how pulling hyperlinks could be added to GDocs support? Right now to my knowledge the content of GDocs is converted in plain text, without hyperlinks. I wonder whether you see a solution for this?

Thanks in advance!

**Comment by pprados** [comment]
Set the parameter `return_link` and try again.
The default value is false because, with an LLM, a URL consumes plenty of tokens.
