### ISSUE TITLE
error  GoogleDriveLoader uthorized user info was not in the expected format

### ISSUE THREAD

**Issue by lespinozacl** [pprados/langchain-googledrive#6]
a 2nd load (call to GoogleDriveLoader) giveme this error:

Authorized user info was not in the expected format, missing fields refresh_token, client_id, client_secret.

**Comment by lespinozacl** [comment]
<img width="811" alt="image" src="https://github.com/pprados/langchain-googledrive/assets/32620612/29f53fd5-a568-4012-93c8-195bb0cdcb20">

**Comment by lespinozacl** [comment]
in your jupyter show the same error
docs/extras/integrations/document_loaders/google_drive.ipynb

**Comment by pprados** [comment]
Hello,
I've fixed the bug in the latest published version
